config/routes.rb
ExampleStore::Application.routes.draw do

  #
  # Shoppe admin interface
  #
  mount Shoppe::Engine => "/shoppe"
  
  #
  # Product browising
  #
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
  
  #
  # Order status
  #
  get 'order/:token' => 'orders#status', :as => 'order_status'

  #
  # Basket
  #
  get 'basket' => 'orders#show', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
  #
  # Checkout
  #
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
  match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch]
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
  #
  # Static pages
  #
  get ':action', :controller => 'pages', :as => 'page'
  
  # 
  # Homepage
  #
  root :to => 'pages#home'
  
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{@page_title} - #{Shoppe.settings.store_name}
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    = yield :head
  %body
    
    %div.demo
      .inner
        %ul.links
          %li= link_to "Play with Shoppe Admin", "/shoppe"
          %li= link_to "Browse the code", "http://github.com/tryshoppe/core"
        %p.text This is a demo store built with #{link_to 'Shoppe', 'http://tryshoppe.com'} - an open source e-commerce platform for Rails.
    
    = display_flash
    
    / The main header displayed on all pages
    / Sometimes will be shorted as the page content dictates. 
    %header.main{:class => @full_header ? 'full' : 'basic'}
      .inner
        / Primary navigation
        %nav.main
          %ul
            %li= link_to "Home", root_path, :nav_item => :home
            %li
              = link_to "Our catalogue", catalogue_path, :nav_item => :catalogue, :class => 'noborder'
              %ul
                - for category in Shoppe::ProductCategory.ordered
                  %li= link_to category.name, products_path(category.permalink)
            %li= link_to "Why shop with us?", page_path(:why), :nav_item => :why
            %li= link_to "FAQs", page_path(:faqs), :nav_item => :faqs
            %li= link_to "Get in touch", page_path(:contact), :nav_item => :contact
          %h1= link_to Shoppe.settings.store_name, root_path
        
        - if @full_header
          %h2 Welcome to our <em>shoppe</em>.
          %p.intro Check out our lovely products on this page and then you can buy them through the website with just a few clicks using our supremely simple ordering system.
      
      - if @full_header
        .bar
          .inner
            %p.call Call us today on <b>01202 901 101</b> if you have any questions.
            %p.offer <b>This week only!</b> FREE next day shipping on all orders over &pound;30.
    
    
    / Main content section
    %section.content
      .inner
      
        / Sidebar
        %section.sidebar
          - if content_for?(:sidebar)
            = yield :sidebar
          - else
            = render 'shared/basket'
            = render 'shared/reasons'
      
        / Primary section
        %section.primary
          = yield
      
    / Footer
    %footer.main
      .inner
      
        / Useful footer links (policies etc...)
        %ul.links
          %li= link_to "Terms & Conditions", page_path(:terms)
          %li= link_to "Privacy policy", page_path(:privacy)
          %li= link_to "Returns policy", page_path(:returns)
          %li= link_to "Frequently asked questions", page_path(:faqs)
          %li= link_to "Cookie policy", page_path(:cookies)
      
        .callUs
          %p Got any questions? Call us today:
          %p.number 01202 901 101
          %p We're open 9am to 5pm, Monday to Friday.
          
          / Links to social media
          %ul.social
            %li.twitter= link_to "Twitter", 'http://twitter.com/niftyware'
            %li.facebook= link_to "Facebook", "http://facebook.com/niftyware"
            %li.pinterest= link_to "Pinterest", "http://pinterest.com"
            %li.linkedin= link_to "Linked In", "http://linkedin.com"
            %li.vimeo= link_to "Vimeo", "http://vimeo.com"
            %li.youtube= link_to "Youtube", "http://youtube.com"
      
        / Copyright & trademark information
        .copyright
          %p &copy; #{Date.today.year} Shoppe. All Rights Reserved.
          %p All third party logos &amp; product images &copy; their respective owners.
          %p
            Shoppe is a trading name of Niftyware Limited.<br />
            Company registration number: 8514362.<br />
            VAT registration number: GB 123 123 123.
          